#!/usr/bin/env python3
# E03_depth_expert.py – Depth High‑Probability Scenario Detector (≥90% setups)
# Input: depth data dict (as generated by X05_depth_rest)
# Output: bias, confidence, high_prob_scenario, signals, reason, etc.

import math

def analyze_depth(depth_data):
    """
    Args:
        depth_data: dict with keys:
            imbalance: float (-1..1)
            current_mid_price: float
            bids_top: list of [price, qty] (top 25)
            asks_top: list of [price, qty] (top 25)
            bids_buckets: dict {bucket_center: volume}
            asks_buckets: dict {bucket_center: volume}
            bids_percentiles: list of {target_pct, price}
            asks_percentiles: list of {target_pct, price}
            bids_tail_stats: dict with total_volume, vwap, std_dev, etc.
            asks_tail_stats: dict
            liquidity_gaps_json: list of gap dicts
            iceberg_bids_json: list of detected icebergs
            iceberg_asks_json: list
    Returns:
        dict with:
            bias: 'bullish'/'bearish'/'neutral'
            confidence: int 0-100 (≥90 indicates high prob)
            high_prob_scenario: 'UP'/'DOWN'/None
            reason: str
            signals: list of str
            net_score: int
    """
    signals = []
    bullish_score = 0
    bearish_score = 0

    # 1. Imbalance ratio (most direct signal)
    imbalance = depth_data.get('imbalance', 0)
    if imbalance > 0.4:
        bullish_score += 30
        signals.append(f"Strong buy imbalance ({imbalance:.2f})")
    elif imbalance > 0.2:
        bullish_score += 15
        signals.append(f"Moderate buy imbalance ({imbalance:.2f})")
    elif imbalance < -0.4:
        bearish_score += 30
        signals.append(f"Strong sell imbalance ({imbalance:.2f})")
    elif imbalance < -0.2:
        bearish_score += 15
        signals.append(f"Moderate sell imbalance ({imbalance:.2f})")

    # 2. Current price relative to volume percentiles (CDF)
    bids_pct = depth_data.get('bids_percentiles', [])
    asks_pct = depth_data.get('asks_percentiles', [])
    mid = depth_data.get('current_mid_price', 0)
    
    bid_price_at_50pct = None
    ask_price_at_50pct = None
    for p in bids_pct:
        if p['target_pct'] == 50:
            bid_price_at_50pct = p['price']
            break
    for p in asks_pct:
        if p['target_pct'] == 50:
            ask_price_at_50pct = p['price']
            break
    
    if bid_price_at_50pct and ask_price_at_50pct:
        # If price is below bid's 50% volume concentration -> support, if above ask's 50% -> resistance
        if mid < bid_price_at_50pct:
            bullish_score += 20
            signals.append("Price below bid volume concentration → support")
        elif mid > ask_price_at_50pct:
            bearish_score += 20
            signals.append("Price above ask volume concentration → resistance")
        else:
            signals.append("Price inside fair value range")

    # 3. VWAP and deviation
    bids_vwap = depth_data.get('bids_tail_stats', {}).get('vwap', 0)
    asks_vwap = depth_data.get('asks_tail_stats', {}).get('vwap', 0)
    if bids_vwap and asks_vwap:
        if mid < bids_vwap:
            bullish_score += 10
            signals.append("Price below bid VWAP → cheap")
        elif mid > asks_vwap:
            bearish_score += 10
            signals.append("Price above ask VWAP → expensive")

    # 4. Liquidity gaps – large gaps can act as vacuum or barriers
    gaps = depth_data.get('liquidity_gaps_json', [])
    large_gaps = [g for g in gaps if g.get('gap_pct', 0) > 0.5]  # >0.5% gap
    gap_above = any(g.get('from_price', 0) > mid for g in large_gaps)
    gap_below = any(g.get('to_price', 0) < mid for g in large_gaps)
    if gap_above and not gap_below:
        bearish_score += 15   # resistance above
        signals.append("Liquidity gap above → resistance")
    elif gap_below and not gap_above:
        bullish_score += 15
        signals.append("Liquidity gap below → support")
    elif gap_above and gap_below:
        signals.append("Liquidity gaps both sides → pending breakout")

    # 5. Iceberg orders – hidden large orders indicate accumulation/distribution
    iceberg_bids = depth_data.get('iceberg_bids_json', [])
    iceberg_asks = depth_data.get('iceberg_asks_json', [])
    if iceberg_bids:
        bullish_score += 20
        signals.append(f"Detected {len(iceberg_bids)} buy iceberg orders")
    if iceberg_asks:
        bearish_score += 20
        signals.append(f"Detected {len(iceberg_asks)} sell iceberg orders")

    # 6. Volume bucket concentration – extreme concentration can signal key level
    # Use bid/ask buckets near mid price (within 0.2%)
    bid_buckets = depth_data.get('bids_buckets', {})
    ask_buckets = depth_data.get('asks_buckets', {})
    # find bucket containing mid
    bucket_size = 0
    for b in list(bid_buckets.keys()) + list(ask_buckets.keys()):
        if abs(b - mid) / mid < 0.0005:  # within 0.05%
            total = bid_buckets.get(b, 0) + ask_buckets.get(b, 0)
            if total > 0:
                signals.append(f"High volume cluster at {b:.1f} ({total:.0f})")
                # no direct score; it's a level
                break

    # 7. Spread between wavg_bid and wavg_ask (if available)
    wavg_bid = depth_data.get('wavg_bid', 0)
    wavg_ask = depth_data.get('wavg_ask', 0)
    if wavg_bid and wavg_ask:
        spread_pct = (wavg_ask - wavg_bid) / mid * 100 if mid else 0
        if spread_pct < 0.02:
            signals.append("Very tight spread → high liquidity")
            # slight bullish bias for tight spread
            bullish_score += 5

    # Compute net score
    net = bullish_score - bearish_score
    net = max(-100, min(100, net))

    # Bias and confidence
    if net >= 30:
        bias = "bullish"
        confidence = min(95, 60 + net // 2)
    elif net <= -30:
        bias = "bearish"
        confidence = min(95, 60 + abs(net) // 2)
    else:
        bias = "neutral"
        confidence = 50 + net // 2 if net else 50

    # High‑probability scenario only if confidence ≥ 90
    high_prob_scenario = None
    if confidence >= 90:
        high_prob_scenario = "UP" if bias == "bullish" else "DOWN" if bias == "bearish" else None

    reason = f"Net score {net:+d}, imbalance {imbalance:.2f}" + (f", {len(iceberg_bids)} icebergs" if iceberg_bids or iceberg_asks else "")
    return {
        "bias": bias,
        "confidence": confidence,
        "high_prob_scenario": high_prob_scenario,
        "probability_estimate": confidence,
        "reason": reason,
        "signals": signals,
        "net_score": net
    }

# Convenience function to directly parse X05's data dict (as returned by update_depth)
def from_x05_data_dict(data_dict):
    """Wrapper for X05_depth_rest's data_dict (the one passed to atomic_write_db)."""
    # data_dict already contains all needed fields.
    return analyze_depth(data_dict)

# Example usage (self-test)
if __name__ == "__main__":
    # Simulate X05 output
    test_depth = {
        "imbalance": 0.45,
        "current_mid_price": 64000,
        "bids_top": [],
        "asks_top": [],
        "bids_buckets": {63980: 500, 64000: 1200, 64020: 300},
        "asks_buckets": {64020: 200, 64040: 800, 64060: 400},
        "bids_percentiles": [{"target_pct": 50, "price": 63950}],
        "asks_percentiles": [{"target_pct": 50, "price": 64080}],
        "bids_tail_stats": {"vwap": 63970},
        "asks_tail_stats": {"vwap": 64090},
        "liquidity_gaps_json": [{"gap_pct": 0.6, "from_price": 64200, "to_price": 64300}],
        "iceberg_bids_json": [{"price": 63900, "qty": 100}],
        "iceberg_asks_json": [],
        "wavg_bid": 63985,
        "wavg_ask": 64015
    }
    result = analyze_depth(test_depth)
    print(result)